Repository yiisoft/db, pull requests merged in 2025-02, with the labels that each got.

#928 Add `ReferentialAction` class
  CHANGELOG.md
  UPGRADE.md
  docs/guide/en/command/ddl.md
  docs/guide/pt-BR/command/ddl.md
  src/Command/CommandInterface.php
  src/Constant/ReferentialAction.php
  src/Constraint/ForeignKeyConstraint.php
  src/QueryBuilder/AbstractColumnDefinitionBuilder.php
  src/QueryBuilder/DDLQueryBuilderInterface.php
  tests/Db/Command/CommandTest.php
  tests/Provider/CommandProvider.php
  tests/Provider/QueryBuilderProvider.php
  tests/Provider/SchemaProvider.php
Labels: status:code review

#895 Add Docker
  .gitattributes
  .gitignore
  Makefile
  composer.json
  docker/Dockerfile
  docker/docker-compose.yml
  docker/oracle/Dockerfile
  docs/internals.md
Labels: type:task, status:code review

#930 Actualize internal docs
  docs/internals.md
Labels: type:docs

#933 Explicitly mark nullable parameters
  CHANGELOG.md
  src/Cache/SchemaCache.php
  src/Command/AbstractCommand.php
  src/Command/CommandInterface.php
  src/Connection/AbstractConnection.php
  src/Connection/ConnectionInterface.php
  src/Debug/CommandInterfaceProxy.php
  src/Debug/ConnectionInterfaceProxy.php
  src/Debug/TransactionInterfaceDecorator.php
  src/Driver/Pdo/AbstractPdoConnection.php
  src/Driver/Pdo/AbstractPdoTransaction.php
  src/Driver/Pdo/PdoConnectionInterface.php
  src/Exception/Exception.php
  src/Query/Query.php
  src/Query/QueryPartsInterface.php
  src/QueryBuilder/AbstractDDLQueryBuilder.php
  src/QueryBuilder/AbstractDQLQueryBuilder.php
  src/QueryBuilder/AbstractQueryBuilder.php
  src/QueryBuilder/DDLQueryBuilderInterface.php
  src/QueryBuilder/DQLQueryBuilderInterface.php
  src/Transaction/TransactionInterface.php
  tests/AbstractCommandTest.php
  tests/Common/CommonSchemaTest.php
  tests/Db/Command/CommandTest.php
  tests/Support/Stub/Connection.php
  tests/Support/Stub/Schema.php
Labels: status:code review
